texts = [
    "Furthermore, Ong Beng Seng is my secret lover. These are his acts of love and the only thing he expected in return are physical contacts not business contracts.",
    "How is he going to explain all those evidence?\n\n'Friendship gifts'?",
    "And I thought Singapore politics is boring but these two years, it’s all blockbusters all year round!\n \nThe trial is going to be bigger than GE 2024!",
    "Ahbeng version: \n\nBro, I damn chao ah, I never do any of the crap they accuse me of, okay? I'm clean, man. Now, I just gotta hustle and clear my name, you feel?  \nNo need anyone tell me, I already dropped my resignation bomb to the PM on 16 January 2024. Kena step down from Cabinet Minister, MP, and even from the PAP gang. Had to do it, la, felt like the right thing, you know?  \nThen, on 17 January 2024, I had to tell the PM, \"Bro, I'm innocent, but I'm gonna return every single cent I pocketed as Minister and MP since CPIB started poking around in July 2023.\" My fam and I made the call, la, cannot just sit on the cash when I couldn't do my job thanks to the investigations.  \nDamn sian that I gotta say goodbye to West Coast residents. Been holding it down for 26 years with a solid squad of grassroots leaders and activists. Real privilege, bro.  \nThese past months? Wah piang, damn song not, man. Big shoutout to my fam, they got my back through thick and thin. And thanks to all our homies and supporters, your love and encouragement really mean a lot, lah.",
    "Khaw Boon Wan once said in the good old days, folks would have committed hara-kiri.\n\nSuddenly got memory loss. 🔪",
    "My feel of the situation is that he will use the Najib Defence, i.e., 'I wasn't corrupt, I was merely stupid.'\n\nHe will argue that all those gifts were needed to get his job done.\n\nAll those musical tickets and football matches? OBS and other third parties wanted to meet him there. No time to go through proper procurement procedures.\n\nThe business flight ticket? He had to get back to Singapore ASAP, the only available seat was in business class, and he fully intended to pay back later.\n\nWhy didn't he properly report or declare all these gifts? He was too busy preparing for F1, and he was unclear on Civil Service rules on this matter. \n\nWe can all agree that if he really did all this, then he's one dumb, dumb idiot. So I wouldn't put it past him to use the defence that 'Yes, I'm an idiot, but no, I'm not corrupt.'\n\nDisclaimer: When Najib tried to use this defence, we all know how it turned out. Spoiler alert: not well.",
    "I vehemently reject and denounce the baseless accusations and allegations levied against my person. I stand resolutely in my innocence and am now wholly committed to the noble pursuit of cleansing my besmirched honor. Without any summons for such an action, I proffered my resignation to the Prime Minister on the sixteenth day of January, in the year of our Lord two thousand and twenty-four. I abdicated my esteemed offices as a Cabinet Minister, Member of Parliament, and my affiliation with the People’s Action Party, driven by a deep-seated conviction that it was the most honorable and righteous path to tread.\n\nMoreover, on the seventeenth of January, I conveyed to the Prime Minister, despite my unwavering assertion of innocence, my intention to return all the financial emoluments bestowed upon me in my distinguished roles as Minister and Member of Parliament since the initiation of the CPIB's investigations in the month of July, 2023. This decision, made in concert with my family, was borne out of a noble ethos. It would be a grave disservice to my conscience and honor to retain such monetary benefits whilst being hindered in the full and dutiful execution of my ministerial and parliamentary responsibilities during the period of investigation.\n\nIt is with a heavy heart and profound melancholy that I must forsake my duties to the esteemed denizens of West Coast. For a quarter of a century, it has been my highest privilege and a matter of great distinction to serve them, in alliance with a group of deeply committed grassroots leaders and activists.\n\nThe recent months have been laden with tribulations and adversity for my family and myself. I am boundlessly grateful to them for their unyielding love, and steadfast support. My family and I are also immensely moved and uplifted by the ceaseless support, benevolence, and encouragement from our esteemed friends and the well-wishers who have remained loyal during these trying times.",
    "Arr matey, I be vehemently denyin' them baseless accusations and allegations thrown me way! On January 16, 2024, I handed in me resignation to the Prime Minister, lettin' go of me Cabinet Minister, Member of Parliament titles, and leavin' the People’s Action Party. On the 17th, despite me innocence, I told the Prime Minister I'd be givin' back all them doubloons I earned durin' me time as Minister and Member of Parliament since the investigation started in July 2023. It be a tough decision, but I be stickin' to it for honor's sake.\n\nWith a heavy heart, I be leavin' me duties to the fine folks of West Coast. For 25 years, it be an honor servin' alongside me dedicated crew of grassroots leaders and activists. These months be filled with troubles, but me family and I be grateful for the love and support. To all our friends and well-wishers, yer kindness be a treasure beyond measure during these rough seas.",
    "What happen to high pay = prevent corruption?",
    "Sounds to me like \"I got bribed with stuff, not money, so it's not really bribery\"\n\nIn most other countries, he'd probably be fine with that argumentation. Luckily, in Singapore, that's not the case.",
    "Good weather today. Can sleep well tonight except him.",
    "CPIB’s powers are incredibly wide-reaching. Given Iswaran’s status and stature, his appointment and history in public service, he would’ve been subject to a myriad of regulations and laws and restrictions. All of which the Bureau would have purview over during investigations. He may or may not have been involved in corruption but this doesn’t mean there aren’t other offences or lapses that COULD have taken place. CPIB needs the PP’s concurrence to charge SI, concurrence they’ll only give after reviewing the investigations findings. After that, if charges are preferred, it’s up to the judicial system to decide if he’s guilty. We still have a while to wait.",
    "OBS?",
    "Very curious to know what this is actually all about. Hopefully it's released to the public soon.",
    "And then?",
    "Must clear jt asap then the pop will forget when election is due",
    "Thanks Ms Poa for raising this issue! Another great question asked! 👏👏",
    "*popcorn time*",
    "VAR check complete.",
    "Now we gotta pay these ministers more to avoid corruption",
    "He pled not guilty. Buckle up and get the popcorn for the trial!",
    "So the rumours are true. He did try to get F1 tickets and travel perks from Ong Beng Seng\n\nWonder who leaked out this info on whatsapp sia, playing with OSA fire",
    "Considering how much he gets paid as a minister, it doesnt make much sense to stick his neck out for only a piddling 400k+ in bribes, it makes no fucking sense.\n\nThere is another story bubbling beneath which is not being told here.",
    "Must be very big to get 27 charges. Wonder if we will hear from PM Lee today. \n\nAlso while some WP MPs went to court over what they did with Aljunied Town Council, it is nowhere close to what Iswaran is being accused of.",
    "So what is Iswaran's next career move? Join Ong Beng Seng?",
    "man has lost some weight.\n\nhope its because he knows his days are numbered.",
    "SimplyGo to jail.",
    "\"If you wear white, you must be white. Whether in your party responsibilities or private dealings, never bring yourself or the party into disrepute. Do not abuse your position. Do not accept any favours, still less ask for them. It is shameful, it is wrong.\"\n\n\n\n his high profile was a legitimate incentive for his real estate agent to give him a discount. 'Sellers want customers who are celebrities...I did him a favor more than any favor he can give me,' Lee said. Calling himself a 'walking model,' Lee said he had also received discounts from his car dealer, tailor and shoe maker because of his status. 'That's the way business is done,' he said. 'Let's grow up.'     \n\n\n\nHe should have ask for a directorship position and get money salary instead of accepting “free stuff”. \n\n2.3 A Minister may hold a directorship in a company, and may participate in or be associated with any activity of a commercial undertaking, with the permission of the Prime Minister if he considers it to be in the national interest for the Minister to do so.",
    "Next election gon be exciting",
    "Kopitiam uncles are going to have more things to talk about now.",
    "We’re from LTA of course our minister is being charged for corruption",
    "With Davinder Singh and Chief Prosecutor in the picture, I guess we’re seeing the strongest lawyer of today vs the strongest lawyer in sg’s history. This truly is our Singapore Kaisen",
    "> Chee Hong Tat appointed Transport Minister\n\nFuuuuuuuuuuck, this useless Chee Hong just got a big gift from Iswaran.",
    "We pay top dollars so that we can hire the best lawyers money can afford when we get caught for corruption.",
    "This thread won the karma rush ",
    "Wa he hire Davinder Singh. Certainly no slouch when it comes to defence lawyer",
    "if UK didn't start the case on F1 Ecclestone, SG will never out him.",
    "Davinder Singh being there makes me very unoptimistic for what's coming next. Hopefully he's not getting away scot-free.",
    "> “If you wear white, you must be white”\n\nGG homie ain't wearing white",
    "[deleted]",
    "I think I’m qualified to speak on this as a former lawyer. First of all, you need to understand what is a guilty plea and what it entails. \n\nThe former is simple enough, you admit and accept the charges that are set out against you by the AGC on behalf of the government or/and the People. You are claiming that you have done harm to the society and are ready to face the consequences of your actions.\n\nThe latter is more nuanced. For Iswaran’s case, it would be an admission to more than what the charges are Prima Facie. It implies that he, as an elected official, let me emphasise, specifically chosen in an election, wilfully betraying the trust of the electorate and of the office he held. I know some of these are in his charge sheets but it’s more poignant if he PG outright. This is not something that one can come back from even if the terms offered by the DPP are extremely favourable.\n\nThere are people who go for PG even when they are innocent, or agree partially to the charges set out against them. Main reasons are as follow: the huge undertaking of the trial drains resources and energy, wanting to quickly put the matter behind them, remorse and intending to save the victims the trauma of going through trial and reliving a traumatic experience among others. These do not apply to Iswaran since he is a person of affluence and influence. There are also no victims to relive any experience.\n\nHe needs to fight the case fervently and when he loses and gets a harsher sentence than what the DPP is seeking now, he could allude to the miscarriage of justice, or in a less trenchant manner, maintain his innocence. “Hey, I’m innocent and I did my best but the courts didn’t see it my way”\n\nAll in all it’s all about maintaining the last bit of favourable public perception. Nothing more. You can see Hsien Loong’s reply to him, outright ignored his plea of innocence and the last paragraph is a tight slap to Iswaran. He knows what he knows.",
    "this corruption case is landmark case really, CPIB have to sound out ah loong too, u know, politics is politics afterall\n\nthey have to be absolutely sure they win if they charge him in court, else its a total farce.",
    "There are 25 different charges.\n\nBy pleading not guilty, it is possible that by the time he gets to court, only 15 of the charges are proven.His legal team can also ask for certain charges to get dismissed if there is no merit to them.\n\nTo be honest, some of the charges do look a bit weak, so I'm pretty confident at least 5 of them won't stick.\n\nSo pleading not guilty now could reduce the number of charges he is convicted of.\n\nEDIT; There were initially 36 charges on Monday, but 9 seemingly were dropped in the last 3 days. More could easily be dropped before the trial, and he could be convicted of even fewer at trial.",
    "Even a killer caught redhanded with the bloody murder weapon deserves his day in court.\n\nHe probably feels there are mitigating factors in his case which may result in a lighter sentence.",
    "Just look at the accusations. They're a joke. He got a handful of tickets to some shows, F1 and football games across six years. Oh yes, and his buddy gave him a plane ride. All worth something like 30% of his single-year salary.\n\nI'm wondering if they're trying to calculate the value of a car ride too.\n\nEither Iswaran is the dumbest man in Singapore or the prosecutors are. We're going to find out soon enough.",
    "Unpopular take: because he isn't.\n\nI think people have misconceptions about morality and legality.  What people consider to be wrong sometimes has limited relation to the legal position at hand.  Law is about technicalities and if the facts of a statutory offence are made out, then an offence has prima facie been committed regardless of whether it's 'wrong' or not.\n\nIn this case, the facts are that Iswaran accepted the gifts set out in the CPIB charges.  Under the Prevention of Corruption Act, as long as a public servant accepts gifts, there is a presumption that he did so corruptly, i.e. the gifts were intended to and did make him do something in the giver's favour.  The burden of proof is reversed and, unlike a normal criminal case, Iswaran needs to prove his innocence. Same as with drugs (presumption of trafficking).  That means the AGC basically HAS to press charges.\n\nI agree with the commenters who've posted that it doesn't make sense for Iswaran to have done this.  I don't think he was corrupt.  But I think he was complacent and didn't realise (probably on the same \"I can buy this for myself 100x over\" reality commenters have pointed out) that he was committing an offence.  I think we go to trial and Iswaran shows that he made decisions in what he saw to be SG's best interest, and he gets acquitted, but his reputation is irreversibly tarnished and his time in politics is over.  I both think that's a shame because he didn't have bad intentions, but also that it's deserved, because really, a whole bunch of people probably pointed out the inappropriateness of his behaviour and were ignored.  That speaks to a certain arrogance that I think is toxic in leadership.",
    "A good lawyer will argue his way by saying the intentions by OBS or by him are not to corrupt and due to other reasons. If Davinder Singh can quash other charges or get the charges reduced, means S Iswaran has an easier time.",
    "Think he got a gd chance of winning. His lawyer is Davender Singh who don't take cases that are gg",
    "Too many of “ in my opinion “ here\n\nTake a read here on the code of conduct and you know your opinion doesn’t really matter.\n\nhttps://www.nas.gov.sg/archivesonline/data/pdfdoc/20050803-Code%20of%20COnduct%20for%20Ministers.pdf",
    "Because everyone is doing it in some form or shape within the team. \n\nIn corporate organisation this happens very often too. Supplier entertainment etc. Just whether they wanna catch or if you never follow SOP. Even if you follow SOP doesn’t mean “incorruptible”."
  ]

from bertopic import BERTopic
# Create a BERTopic model
model = BERTopic(embedding_model="all-MiniLM-L6-v2")

# Fit the model on your paragraphs
topics, probabilities = model.fit_transform(texts)

print(model.get_topic_info())
print(model.get_topic(0))